version: "3.8"
services:
  webserver:
    container_name: php-apache
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./conf:/usr/local/etc/php/conf.d
    ports:
      - 8000:80
      - 9000:9000
    depends_on:
      - db

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "9906:3306"
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - 8080:80
      